name: Train and Upload Model

on:
  release:
    types: [published]

jobs:
  train-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install language-pack-en
        run: sudo apt-get update && \
            sudo apt-get install -y language-pack-en language-pack-en-base

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install coloredlogs flatbuffers numpy packaging protobuf sympy
          python -m pip install -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/ --pre onnxruntime

      - name: Run training script
        run: |
          python train_cve_multilabel_classifier.py

      - name: Upload model to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cve_multilabel_classifier.onnx
